### ISSUE TITLE
1.8.0 release failed

### ISSUE THREAD

**Issue by mjfwebb** [srvaroa/labeler#114]
@srvaroa https://github.com/srvaroa/labeler/actions/runs/6943962687 the release didn't work properly so the actions weren't created. Referring to the missing actions tar in the release downloads here: https://github.com/srvaroa/labeler/releases/tag/v1.8.0

Here's the failing action: https://github.com/srvaroa/labeler/actions/runs/6943962687

_Originally posted by @mjfwebb in https://github.com/srvaroa/labeler/issues/113#issuecomment-1821009505_

**Comment by srvaroa** [comment]
Looks like there is an issue in the runners that doesn't populate the GITHUB_REF variable sporadically, which makes the go-release action fail. I changed it to a manual release so I can feed the tag by hand. It looks like it works now, and i've updated the `v1` floating reference, as well as the default version in `Dockerfile`

I'll wait before closing this in case someone screams, otherwise close soon.

Thanks @mjfwebb!

**Comment by srvaroa** [comment]
I've ran a test PR with the latest release and things look ok.

I'll close for now, but let me know if any issue appears. https://github.com/srvaroa/labeler/actions/runs/6945949126/job/18896413696?pr=116
