### ISSUE TITLE
Github Action: pull_request_target not supported

### ISSUE THREAD

**Issue by akinsolb** [srvaroa/labeler#13]
I have added this GitHub action to my repo with the event type: `pull_request_target` instead of `pull_request`. This seems to run on the base repository as expected but I get the following error message:

`2020/09/11 18:18:35 Trigger event: pull_request_target`
`2020/09/11 18:18:35 Unable to execute action: unknown X-Github-Event in message: pull_request_target`

Is there anyway this can be supported?

**Comment by srvaroa** [comment]
Hi, thanks for trying it out. It depends on the go-github library supporting that event. On a quick inspection it looks like the latest version doesn't support it yet (https://github.com/google/go-github/blob/159b448168db1fc1bc61a556e6280e12dfc00a6d/github/messages.go#L43).  If you can make a feature request there I'm able to integrate it fairly quickly once it's available.

I may be able to implement it myself but can't promise it'll be too fast.

**Comment by srvaroa** [comment]
I just noticed there is an [open PR](https://github.com/google/go-github/pull/1619) for that new event type so it'll hopefully get merged soon.

**Comment by srvaroa** [comment]
It's been merged, I'll wait for a release and upgrade.

**Comment by kbendick** [comment]
Hi @srvaroa, has this been fixed? The `pull_request_target` is important for repos where people fork and submit PRs but don't necessarily have write access. For example, many of the Apache repos. The example github labeler action doesn't support the features that we need for the Apache Spark repo.

If this has been merged, can you cut a release or let me know which release version needs to be used so that `pull_request_target` is supported?

**Comment by srvaroa** [comment]
Hi @kbendick I haven't seen a release including that PR yet.  What we can do is try to bump the go-github version and use the current master so we can see that event before they publish a final release.  I can try this this week, but do feel free to send a PR!

**Comment by akinsolb** [comment]
@srvaroa Think this might be out now

**Comment by srvaroa** [comment]
Thanks for the heads up @akinsolb I'll take a look

**Comment by jhlegarreta** [comment]
@srvaroa folks at goolge said that the feature in the PR mentioned in https://github.com/srvaroa/labeler/issues/13#issuecomment-691487714 will cut into a release within the next few hours/maybe a day or two.

Now, inspecting the [webhook event mapping you pointed](https://github.com/google/go-github/blob/master/github/messages.go#L79), that PR does not include the `pull_request_target` event. So I'm wondering whether the mentioned PR does in reality contain what is necessary to support `pull_request_target` events in your PR labeler action or else the mapping would still be missing. Looking forward to the feature. Thanks.

**Comment by gmlewis** [comment]
Thank you, @jhlegarreta - it looks like we haven't implemented support for that webhook event.  I've opened a new issue to support it: https://github.com/google/go-github/issues/1834

**Comment by jhlegarreta** [comment]
`go-github` [now provides support](https://github.com/google/go-github/blob/master/github/messages.go#L80) for `pull_request_targert` events :tada:.

@srvaroa provided that they tag a new version (they do that on demand), do you think that is enough to support them in the `labeler` actions/would have the time to implement it? Maybe an attempt on the `go-github` might cast light on whether something is still missing on that end? Thanks.

**Comment by gmlewis** [comment]
So a tagged release of `go-github` would be useful here?  If so, I can start working on one.

**Comment by gmlewis** [comment]
I finally got an LGTM, so https://github.com/google/go-github/releases/tag/v35.0.0 has now been released.

**Comment by jhlegarreta** [comment]
Wonderful @gmlewis. Thanks !

@srvaroa any progress on this would be much appreciated !

**Comment by srvaroa** [comment]
Hi, thanks @gmlewis  and @jhlegarreta, I've just submitted a PR that should make this work.  I can't test it more thoroughly now but if you can try it out (using `srvaroa/labeller@g.dev`) it'd be appreciated.  A sample payload that I can add to a test would also help.

PR: https://github.com/srvaroa/labeler/pull/27

Cheer,

**Comment by jhlegarreta** [comment]
Thanks for the effort @srvaroa :+1:.

Unfortunately, it looks like the first attempt was unsuccessful here:
https://github.com/InsightSoftwareConsortium/ITK/runs/2427975641?check_suite_focus=true#step:3:78

But that's because the workflow is still attempting to use the `master` branch:
https://github.com/InsightSoftwareConsortium/ITK/runs/2427975641?check_suite_focus=true#step:3:1

And I fear that unless I merge the PR, we will not know if the changes in #27 work for the target use case. I'd like to avoid doing various merge and revert cycles or tests on that repository for many reasons :pensive:.

Maybe your or I can open a test repository that includes an action that uses your labeler, and the other one can try submitting a PR to see if `pull_request_target`-like events are working off the branch in #27?

**Comment by jhlegarreta** [comment]
For the records, following the above comment we tested the branch in another repository and the action labeled the issue :rocket: !

Besides, the action creates the corresponding label if it does not exist when a match is found in the configuration file.

Thnx @srvaroa :100: !
